version: '3'
services:
  postgres:
    build:
      context: .  # Constrói a imagem do PostgreSQL a partir da raiz
      dockerfile: Dockerfile.postgres  # Especifica o Dockerfile correto para o PostgreSQL
    container_name: pgs_cohmetrix
    environment:
      POSTGRES_USER: cohmetrix
      POSTGRES_PASSWORD: cohmetrix
      POSTGRES_DB: cohmetrix
    volumes:
      - ./tools/postgres:/shared  # Volume com o backup do banco
      - ./initdb:/docker-entrypoint-initdb.d  # Scripts de inicialização
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pgnetwork

  app:
    build:
      context: .  # Caminho para o diretório raiz onde o Dockerfile da aplicação está
      dockerfile: Dockerfile.python  # Nome do Dockerfile específico da aplicação
    container_name: python_app
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: cohmetrix
      POSTGRES_PASSWORD: cohmetrix
      POSTGRES_DB: cohmetrix
      POSTGRES_HOST: postgres  # Aponta para o serviço 'postgres' no network
    volumes:
      - ./text_metrics:/opt/text_metrics  # Mapeia a pasta text_metrics
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
